services:

  spark-master:
    image: apache/spark:3.5.8
    container_name: spark-master
    hostname: spark-master

    command:
      - /opt/spark/bin/spark-class
      - org.apache.spark.deploy.master.Master
      - --host
      - spark-master
      - --port
      - "7077"
      - --webui-port
      - "8080"

    ports:
      - "8180:8080"
      - "7077:7077"
      - "4040:4040"

    volumes:
      - ./data:/opt/spark/data:ro
      - ./jobs:/opt/spark/jobs:ro
      - ./output:/opt/spark/output
      - ./evidence:/opt/spark/evidence

    networks:
      - spark-network


  spark-worker-1:
    image: apache/spark:3.5.8
    container_name: spark-worker-1
    hostname: spark-worker-1

    command:
      - /opt/spark/bin/spark-class
      - org.apache.spark.deploy.worker.Worker
      - spark://spark-master:7077
      - --cores
      - "2"
      - --memory
      - "2G"
      - --webui-port
      - "8081"

    depends_on:
      - spark-master

    ports:
      - "8181:8081"

    volumes:
      - ./data:/opt/spark/data:ro
      - ./jobs:/opt/spark/jobs:ro
      - ./output:/opt/spark/output

    networks:
      - spark-network


  spark-worker-2:
    image: apache/spark:3.5.8
    container_name: spark-worker-2
    hostname: spark-worker-2

    command:
      - /opt/spark/bin/spark-class
      - org.apache.spark.deploy.worker.Worker
      - spark://spark-master:7077
      - --cores
      - "2"
      - --memory
      - "2G"
      - --webui-port
      - "8081"

    depends_on:
      - spark-master

    ports:
      - "8182:8081"

    volumes:
      - ./data:/opt/spark/data:ro
      - ./jobs:/opt/spark/jobs:ro
      - ./output:/opt/spark/output

    networks:
      - spark-network


  spark-history:
    image: apache/spark:3.5.8
    container_name: spark-history
    hostname: spark-history

    command:
      - /opt/spark/bin/spark-class
      - org.apache.spark.deploy.history.HistoryServer

    environment:
      - SPARK_HISTORY_OPTS=-Dspark.history.fs.logDirectory=/opt/spark/output/spark-events -Dspark.history.ui.port=18080 -Dspark.history.fs.update.interval=5s

    depends_on:
      - spark-master

    ports:
      - "18080:18080"

    volumes:
      - ./output:/opt/spark/output

    networks:
      - spark-network


networks:
  spark-network:
    driver: bridge